homeassistant:
  latitude: !secret latitude_home
  longitude: !secret longitude_home
  elevation: !secret elevation_home
  name: Home
  temperature_unit: C
  time_zone: Europe/London
  unit_system: metric
